apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nginx.udomomo.com
spec:
  group: udomomo.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        OpenAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                version:
                  type: string
  scope: Namespaced
    names:
      plural: nginx
      singular: nginx
      kind: Nginx
      shortNames:
        - ngx